### ISSUE TITLE
Problem with ops marked as not fetchable.

### ISSUE THREAD

**Issue by dekromp** [Thenerdstation/mltest#2]
Hi,
I encountered an issue with ops that are marked as not fetchable in `assert_never_nan`.

Minimal example that reproduces the error:
```python
import numpy as np
import tensorflow as tf
from mltest.mltest import op_dependencies


# Simple dummy graph that contains not fetchable ops.
x = tf.placeholder(tf.float32, [None, 10])
is_training = tf.placeholder(tf.bool, [])
do = tf.layers.dropout(x, rate=0.5, training=is_training)

# Get the parent ops.
parent_ops = op_dependencies(do)

# Some random data.
feed_dict = {x: np.random.uniform(-1, 1, size=(8, 10)).astype(np.float32),
             is_training: True}

# Run each op
with tf.Session() as session:
    parent_ops = op_dependencies(do)
    results = session.run(parent_ops, feed_dict=feed_dict)
```

This causes:
```
Traceback (most recent call last):
  File "minimal_mltest_bug.py", line 16, in <module>
    results = session.run(parent_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1113, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 433, in __init__
    self._assert_fetchable(graph, fetch.op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 446, in _assert_fetchable
    'Operation %r has been marked as not fetchable.' % op.name)
ValueError: Operation u'dropout/cond/Identity' has been marked as not fetchable.
```

One way to fix this could be to filter the ops returned by op_dependencies, maybe like this:
```python
graph = tf.get_default_graph()
filtered_ops = [op for op in parent_ops if graph.is_fetchable(op)
```

What do you think?

**Comment by chaserileyroberts** [comment]
This seems to be a problem with tf.cond() and tf.while() just in general. 

I added your recommendation to the [unfetchable branch](https://github.com/Thenerdstation/mltest/tree/unfetchable), but it doesn't work when a NaN happens inside of a tf.cond

https://travis-ci.org/Thenerdstation/mltest/jobs/374481637

I'm still trying to figure out how detect NaNs and Infs inside of conditional branches, until then, if you need I can add the fix and push it as 0.1.3. I'll give it some more research this week.

**Comment by chaserileyroberts** [comment]
Pushed your recommendation to 0.1.3.

**Comment by dekromp** [comment]
Thx a lot!
