### ISSUE TITLE
Errors with TF 2.0

### ISSUE THREAD

**Issue by gndowns** [Thenerdstation/mltest#8]
This issue is meant to be a place to discuss all issues related to usage with Tensorflow 2.0, and potential robust solutions

## Issues

1. tensorflow has no attribute reset_default_graph

**command:**
```
>>> import mltest
>>> mltest.setup()
```

**output:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gdowns/venv_mltest/lib/python3.7/site-packages/mltest/mltest.py", line 39, in setup
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'
```

## Potential Long-Term Solutions
- Modifying mltest to fit TF2.0 API
- Creating a fork mltest2.0

**Comment by ucalyptus** [comment]
for my machine with Python 3.6.8 and now TF 1.14.0

`import mltest
mltest.setup()
`
gives the warning of deprecation for reset_default_graph()

and suggests to use tf.compat.v1.reset_default_graph()
 Guess I'll add that

**Comment by ucalyptus** [comment]
@gndowns any updates?

**Comment by gndowns** [comment]
@ucalyptus Sorry but I am no longer working on this.

**Comment by chaserileyroberts** [comment]
I think it sadly has come time to deprecate this library...

**Comment by bmiselis** [comment]
Are you planning to create a new version of it or know any alternatives?

**Comment by chaserileyroberts** [comment]
At this time no.

Many of the things we were testing against are ready features of Keras, mainly the "make sure all variables get trained" has been in keras even before this library existed.

However, if someone wishes to port this to TF2, I'd gladly link it here like I did with the Pytorch version.

**Comment by zaccharieramzi** [comment]
@Thenerdstation do you know if those ready features of Keras were ported to tf.keras in Tf 2.x?

I have been looking around a bit in [here](https://www.tensorflow.org/api_docs/python/tf/test) but didn't find anything satisfactory.
